import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Header from "./components/header/header";


const sora = Sora({
  variable:"--font-sora-sans",
  subsets:["latin"],
})

export const metadata: Metadata = {
  title: "OpenPath",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
