import type { Metadata } from "next";
import { Geist, Geist_Mono, Sora } from "next/font/google";
import "./globals.css";
import Header from "./components/header/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  weight:["300","400","500","700"],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sora = Sora({
  variable:"--font-sora-sans",
  subsets:["latin"],
})

export const metadata: Metadata = {
  title: "OpenPath",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
